import string
import os
from excluded import excluded_words

# Needs to contain at least one nested list, like this --> USABLE_CHARS = [['*','3']]
USABLE_CHARS = [
        list(string.ascii_lowercase),
        list(string.ascii_uppercase),
        list(string.digits),
        list(string.punctuation),
]

# A list of characters which will not be used in password generation.
EXCLUDED_CHARS = ['a','b','B','3','=']

# A list of words or phrases which will, if found, be replaces in the password.
# For more details please see excluded.py
EXCLUDED_WORDS = excluded_words

# Minimum number of password characters.
MIN_PASS_LEN = 8

# Maximum number of password characters.
MAX_PASS_LEN = 20

# Setting a fixed password length. Set to False to disable, set to a number to enable.
FIXED_LEN = False

# Default number of passwords which will be generated by generate_password and generate_human_password.
PSWRD_NO = 1

ROOT_DIR = os.getcwd()

TEMPLATE_DIR = os.path.join(ROOT_DIR, 'templates')

MODEL_DIR = os.path.join(ROOT_DIR, 'models')

MIN_SENT_LENGTH = 10
